server:
  port: 9002
spring:
  messages:
    encoding: UTF-8
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: localhost
    password: 
    # Redis服务器连接端口
    port: 6379
    timeout: 20000
logging:
  config: classpath:logback-spring.xml
fc: 
  storage: 
    active: ipfs
    local:
      storagePath: static
      address: 
    ipfs:
      host: localhost
      port: 123
      localPath: 
      downloadPort: 456
      requestBase: 
      remoteService: 